### ISSUE TITLE
Intersection - undefined

### ISSUE THREAD

**Issue by hog-seruj** [Splidejs/splide-extension-intersection#1]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.1.4

### Description

I try to import the Intersection extension but the object is empty and mount I see the error: 'Component is not a function`.
I'm using webpack.

### Steps to Reproduce

import Splide from '@splidejs/splide';
import { Intersection } from '@splidejs/splide-extension-intersection';

new Splide('@slider').mount({ Intersection });

### Expected Behaviour

The intersection object is not undefined.

**Comment by NaotoshiFujita** [comment]
I've updated the package. Can you try the v0.1.5?

**Comment by hog-seruj** [comment]
I see the same issue.

**Comment by NaotoshiFujita** [comment]
Mmm, I have no idea. It's working correctly:
https://codesandbox.io/s/musing-wind-06gug

**Comment by hog-seruj** [comment]
With your example I have this error:
`./node_modules/@splidejs/splide-extension-intersection/dist/js/splide-extension-intersection.esm.js 118:31Module parse failed: Unexpected token (118:31)You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders|     autoScroll: {|       enable() {>         Components2.AutoScroll?.play();|       },|       disable() {`

**Comment by hog-seruj** [comment]
On my side I see this error:
`./node_modules/@splidejs/splide-extension-intersection/dist/js/splide-extension-intersection.esm.js 118:31Module parse failed: Unexpected token (118:31)You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders|     autoScroll: {|       enable() {>         Components2.AutoScroll?.play();|       },|       disable() {`

**Comment by NaotoshiFujita** [comment]
Ah, I see. Old webpack cannot understand optional chaining. Using webpack 5 will solve the problem.

**Comment by hog-seruj** [comment]
In my current project, I can't update the webpack. Is any way to solve the issue in splide-extension-intersection?

**Comment by NaotoshiFujita** [comment]
Mmm. You can manually babel the esm file if you in a hurry:
https://babeljs.io/

I can do it on my side, but I'm busy in this week.

**Comment by NaotoshiFujita** [comment]
Optional chaining has been removed in ^0.1.6
