### ISSUE TITLE
window.splide.Extensions is undefined

### ISSUE THREAD

**Issue by nicmare** [Splidejs/splide-extension-intersection#2]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

4.0.1

### Description

I run splide 4 via Hosting File as described here https://splidejs.com/guides/getting-started/ and wanted to add the intersection extension as described here https://splidejs.com/extensions/intersection/#usage

but it does not work. window.splide.Extensions is simply "undefined".
what do i miss here? i also inspected the window variable but could not find any splide extensions!

```
var splide = new Splide( '.splide',{
                type   : 'loop',
                perPage: 1,
                lazyLoad: 'nearby',
                pagination: false,
                autoplay: 'pause',
                intersection: {
                    inView: {
                        autoplay: true,
                    },
                    outView: {
                        autoplay: false,
                    },
                },
            } );
            splide.mount(window.splide.Extensions);
            console.log(window.splide); // undefined
```

splide in general works pretty good but i don't get the extension started

### Steps to Reproduce

1. setup splide https://splidejs.com/guides/getting-started/#hosting-files
2. follow guide from [```](https://splidejs.com/extensions/intersection/#cdn-or-hosting-files)
...

### Expected Behaviour

nice autoplay feature when gallery comes into viewport

**Comment by NaotoshiFujita** [comment]
The local variable `var splide` overwrites the global `window.splide`. Simply rename it like:

```js
var yourSlider = new Splide( '.splide',{
    ...
} );
yourSlider.mount(window.splide.Extensions);
console.log(window.carousel );
```

or store extensions in another variable:

```js
var Extensions = window.splide.Extensions;
var splide = new Splide( '.splide',{
    ...
} );
splide.mount(Extensions);
console.log(Extensions);
```

**Comment by nicmare** [comment]
oh wow sure thats make sense. story for my stupidness ;-)
