### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'dispatchEvent')

### ISSUE THREAD

**Issue by varshaAggarwal07** [Splidejs/splide-extension-intersection#3]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v0.2.0

### Description

<img width="715" alt="Screenshot 2022-06-30 at 4 51 22 PM" src="https://user-images.githubusercontent.com/93185127/176665253-62d5a946-fcbe-4090-a533-c7d7a7de375c.png">

### Steps to Reproduce

1.import { Intersection } from "@splidejs/splide-extension-intersection"; 
2.Give these options to Splide component <Splide
		options={{
			rewind: true,
			perPage: 3,
			gap: "2rem",
			breakpoints: {
				1150: {
					perPage: 2,
					gap: ".7rem",
				},
				800: {
					perPage: 1,
					gap: ".7rem",
				},
			},
			interval: 5000,
			pauseOnFocus: true,
			resetProgress: true,
			autoplay: "pause",
			intersection: {
				inView: {
					autoplay: true,
				},
				outView: {
					autoplay: false,
				},
			},
		}}
		extensions={{ Intersection }}>
...3. Bring Splide slider in viewport or out of viewport

### Expected Behaviour

It is working well functional wise but giving this error in console(refer to the attached image in Description)

**Comment by dsaket** [comment]
@NaotoshiFujita any update on this...I'm facing the similar issue :(

**Comment by NaotoshiFujita** [comment]
I could not reproduce the issue.
https://codesandbox.io/s/3-54h9lk

Please fork it and reproduce the bug.
